### PR TITLE
Use relative paths to mimic `require` behaviour

### PR DESCRIPTION
**Pull request by jpwilliams**
Working and looks like tests are passing but need README info and added tests for the relative paths.

### CODE REVIEW

**Comment by jpwilliams** [comment]
I think this would require a major version bump up to `2.0.0` as well?

**Comment by jacktuck** [comment]
Looks good 👍 

I wouldn't worry about bumping the version, but if you wanted backwards compatability you could have a default `working_dir` of the CWD?

**Comment by jpwilliams** [comment]
@jacktuck Would be nice but all of the `working_dir` figuring out's internal, so it'd automatically grab the relative path rather than anything we could supply.

We _could_ offer the ability to provide your own `working_dir`, but I think that's probably a bit far.

**Comment by jpwilliams** [comment]
So if we directly `require` and use _microboot_, we're fine. If, however, we `require` a file which _then_ `require`s _microboot_ and that _initial_ file calls it, we're screwed.

Instead of setting the `working_dir` upon being `require`d, we should probably set it upon being called. Something like [this](http://stackoverflow.com/a/19788257/6198535) might do the trick.

_Definitely_ needs tests for this circumstance too.

**Comment by jacktuck** [comment]
That does seem to work.

However, if you do call the function from the same file as it is defined in, without requiring it from elsewhere, the you will not get any path but rather `module.js`. Which 

``` javascript
function _getCallerFile() {
    try {
        var err = new Error();
        var callerfile;
        var currentfile;

        Error.prepareStackTrace = function (err, stack) { return stack; };

        currentfile = err.stack.shift().getFileName();

        while (err.stack.length) {
            callerfile = err.stack.shift().getFileName();

            if(currentfile !== callerfile) return callerfile;
        }
    } catch (err) {}
    return undefined;
}

a = _getCallerFile()
console.log(a)
//a = module.js
```

I suppose that it won't every be called from within the same file though, so should be fine, i'd think.

**Comment by jpwilliams** [comment]
@jacktuck How d'ya mean? Example of it dying? :)

**Comment by jpwilliams** [comment]
Ah I see, @jacktuck. If that's only an issue if we `microboot()` inside _microboot_ then yeah, non-issue.

Then again, would this affect the use-case whereby a `microboot()` loaded a file that called another `microboot()`? I guess we should support that, however mad an idea it is?

**Comment by jpwilliams** [comment]
Interesting. So using that above code returns the file that _eventually_ called `up()`, so in testing we end up getting `working_dir`s of `/Users/username/microboot/node_modules/chai/lib/chai/core` due to the use of `bind()` and the like.

Maybe worth looking into [how _node.js_ itself does it with `require()`](https://github.com/nodejs/node/blob/master/lib/module.js)?

**Comment by jacktuck** [comment]
Yeah `.bind` and such will throw a spanner in the works here.

**Comment by jpwilliams** [comment]
After that bug just now, @jacktuck, it's probably a good idea to just settle with something like `process.mainModule.filename` as the main directory and `resolve` from there?

``` js
require(require('path').resolve(process.mainModule.filename, file))
```

Wouldn't achieve relativity, but would at least keep it consistent compared to `process.cwd()`.

**Comment by jpwilliams** [comment]
Closing due to #19 and the fact that this doesn't reliably work.

**Pull request closed without merging**
